export type JournalBlock = { h2?: string; body: string };

export type JournalPost = {
  slug: string;
  title: string;
  /** One-sentence teaser for the hub card — not copied verbatim from the post. */
  dek: string;
  date: string; // ISO
  blocks: JournalBlock[];
};

export const journal: JournalPost[] = [
  {
    slug: "the-golf-ball-in-my-throat",
    title: "The Golf Ball in My Throat: An Australian's Reluctant Medical Adventure in Hainan",
    dek: "A golf-ball-sized cyst, a missed flight home, and ten days of proving that even the founder isn't always smarter than his own denial.",
    date: "2026-07-31",
    blocks: [
      {
        body: "If there's one thing a former luxury concierge and student of traditional Chinese medicine should know, it's when to ask for help. But apparently, like a stubborn mule who's read too many WebMD articles, I decided to meet my own medical emergency with a cocktail of denial, over-the-counter painkillers, and a 6 AM flight.",
      },
      {
        body: "What unfolded in December 2023 wasn't just a health scare; it was an unexpected, behind-the-scenes tour of Hainan's world-class medical infrastructure — a journey that began with me thinking I had a common cold and ended with a specialist pulling a vial of unmentionable fluid from a cyst the size of a golf ball that was practically throwing a rave on my right tonsil. This is the story of how Hainan, the \"Hawaii of China,\" saved me from my own stupidity, and why this tropical island should be your next destination not just for the coconuts, but for cutting-edge care.",
      },
      {
        h2: "The Shanghai Surprise (That I Ignored)",
        body: "It was early December. I was in Shanghai for an event, riding high on the buzz of the city, when a sharp, stabbing pain set up camp in my right ear. My throat felt like I'd swallowed a cactus. With a background steeped in natural therapies and acupuncture, my diagnostic brain kicked in: Ah, the beginning of a common cold. I've got this.\n\nSpoiler alert: I did not, in fact, have this.\n\nWithin 24 hours, a fever hit me like a freight train. I spent an entire day melting into a friend's mattress, missing the very event I'd traveled for. At 1 AM, in that strange, lucid clarity that only a high fever brings, I realized I was about to get very, very sick. Instead of doing the logical thing and finding a hospital in Shanghai, I pulled the classic expat maneuver: \"I need to get home.\" I mainlined painkillers, booked the first flight back to Haikou, and by 10 AM, I was dragging my rapidly deteriorating body across the threshold of my compound, opposite the Hainan Cancer Hospital.",
      },
      {
        h2: "The Ten-Day Death March (At Home)",
        body: "For the next ten days, I performed an Oscar-worthy act of self-deception. I wasn't just sick; I was engaged in a grim science experiment on how long a human can go without water. My throat didn't just hurt; it sealed shut. We're talking a total blockade. Attempting to swallow a drop of water felt like asking a concrete wall to absorb a tennis ball. I became a husk of a man — severely dehydrated, vaguely delirious, communicating only in pained grunts and regretful glances. I lost weight I didn't have to lose and hadn't touched solid food since the memory of what chewing felt like was a distant dream.\n\nFinally, beaten by my own body, I mustered the staggering amount of energy required to walk across the road.",
      },
      {
        h2: "A Modern Mirage in the Tropics",
        body: "I shuffled into the Emergency Department of the Hainan Cancer Hospital, a place I'd stared at for years from my balcony, never imagining I'd be a character in its story. I looked like death warmed up. When the triage nurse asked what was wrong, I opened my mouth and produced only a breathy, rattling silence. I had zero voice. Pointing frantically at my throat and mumbling in text via a translator app, I must have looked like a fever-dream mime.\n\nThen, the first stroke of luck hit. The Ear, Nose, and Throat (ENT) specialist happened to be on duty. In my experience, \"ENT specialist on duty in the ER\" is usually code for \"wait three weeks for an appointment.\" Not here. He appeared quickly, took one look down my throat with a scope, and his expression said what I already felt: This is a problem. He spoke fluent English, which was a blessing because my ability to mime \"airway obstruction\" was reaching its artistic limit.\n\nHe calmly informed me that I had a massive cyst, perched on my right tonsil, gleefully threatening to cut off my air supply. \"We need to do a procedure,\" he said, with the kind of steady assurance you desperately need in that moment. \"Now.\" Without general anesthetic, but with a mountain of reassurance, he guided a large syringe needle into the cyst and drained a full vial of something. I won't describe it. I want you to keep reading.\n\nThe relief was almost biblical. I could breathe. It was just the overture, though. The cyst re-inflated overnight, only to pull a dramatic self-destruction while I was gargling the next morning. When I returned to the hospital, looking like a bedraggled survivor, the doctor nodded sagely. The infection had flooded my bloodstream, gifting me a stubborn fever and a stark realization: I hadn't eaten in over 10 days. I was running on fumes and bad decisions.",
      },
      {
        h2: "The IV Lounge: Where Healing Happens",
        body: "The doctor prescribed a 10-day course of intravenous antibiotics. Now, in many countries, that means a hospital admission. Here, it's an elegant daily ritual. Every afternoon, I'd walk back across the road, see the specialist after a wait of less than ten minutes (I timed it; the efficiency is a special kind of magic), get my script, pay a fee so nominal it felt like a rounding error, and pick up my IV meds at the pharmacy counter. They'd plop the basket of bottles into my hands, and I'd wander over to the IV infusion department.\n\nNow, this hospital is not a hospital in the grim, linoleum-and-grief sense. It has escalators. Glass elevators. It's spotlessly, almost intimidatingly clean. It's like a shopping center dedicated to not dying. I'd sit in a comfortable recliner among other patients, and a nurse would hook me up. For two to four hours, I'd sit there, rehydrating and receiving the most powerful antibiotics directly into my system — a standard and highly effective Chinese medical practice that completely bypasses the digestive drama of oral meds.",
      },
      {
        h2: "The Handshake That Changed Everything",
        body: "Here's where the story pivots from a personal medical win to a service revelation. On that first terrifying day, the hospital allocated an English-speaking staff member to me. He found me through a WeChat message, a digital guardian angel, and for the duration of my treatment, he was my guide. He'd help me navigate the registration, stand with me at the specialist's door, and chat with me while the IV dripped. It wasn't just translation; it was hospitality-infused healthcare. It was the VIP luxury service of my Beijing past, but delivered in a public hospital setting.\n\nI was an idiot for waiting ten days. The fear of a Chinese hospital — the language barrier, the bureaucracy, the unknown — had paralyzed me. In hindsight, the entire process was more streamlined than any medical system I've encountered in the West. From the cashier to the pharmacy to the IV chair, I was shepherded with a level of care that transformed a daunting ordeal into a strangely calming daily routine.",
      },
      {
        h2: "Don't Be Me: The Hainan Medical Tourism Wake-Up Call",
        body: "Two weeks after my IV course ended, I saw the surgeon again. He did a final scope. \"Perfectly clear,\" he smiled. \"No need to remove the tonsils now. It might have been a one-off infection. But if it ever happens again...\" He left the threat of a tonsillectomy hanging in the air. I got the message. Listen to your body before it mutinies.\n\nI'd suffered in abject misery for ten days because of my own arrogance, thinking I could outsmart a golf ball-sized cyst with cold medicine. My suffering was completely unnecessary.\n\nThis experience crystalized why I am so fiercely passionate about what we do here. Hainan isn't just the \"Hawaii of China\" with its palm-lined beaches and volcanic parks. It's a Special Medical Zone where policies allow for state-of-the-art technologies and protocols — in both Western and Traditional Chinese Medicine — that are on the absolute frontier of longevity and anti-aging. The Hainan Cancer Hospital, with its smart escalators and five-star hygiene, is just one gleaming node in this health ecosystem.\n\nFor anyone out there Googling \"medical tourism\" through fingers clenched in fear, thinking China is too difficult, too foreign, or too daunting: rest assured. This Australian expat, a man who once lived in five-star hotels and studied the meridians of the body, was reduced to a voiceless puddle and put back together again with incredible efficiency and warmth. We have the team, the direct affiliations, the translators, and the local knowledge to make your journey not just painless, but a luxury health retreat.\n\nYou'll get the treatment that hasn't reached your home country yet, on an island that feels like a permanent vacation. And trust me, if I can walk into an emergency room, communicate through a mix of throat rasps and smartphone screen flashing, and walk out with a bill that didn't even warrant an insurance claim, so can you. Just don't wait ten days to do it. Be smarter than me. Almost everyone is.",
      },
    ],
  },
  {
    slug: "midstream-mishaps-to-brain-scans",
    title: "From Midstream Mishaps to Brain Scans: My Full-Body Health Audit in a Hainan Medical Center",
    dek: "The premeditated, grown-up sequel: a full-body screening, a surgeon-friend who drove two hours before dawn, and the biggest iced coffee of the founder's life.",
    date: "2026-08-06",
    blocks: [
      {
        body: "If my last Hainan medical chapter was an unplanned sprint to the emergency room with a golf ball-sized cyst threatening to turn my throat into a one-way street, this one was the premeditated, grown-up version: a full-body screening so comprehensive it would make a hypochondriac blush. And it began, poetically, with a sleepless night, a 4:30 AM surrender to insomnia, and the cruel, cruel absence of coffee.",
      },
      {
        body: "The date: August 6th, 2026. The mission: the \"Full Monty\" of health checks — bloodwork, imaging, and the kind of intimate probing that answers the question, What exactly is going on in there? My last blood test was a casual fling in Thailand back in July 2025. This time, I wanted the deep data. Inflammatory markers, organ function, and a cranial MRI that would finally prove whether my brain was indeed still in there. My alarm screamed at 7:00 AM after roughly two and a half hours of anxious half-sleep. No food. No coffee. Just me, a dry mouth, and a 40-minute Didi ride downtown toward a sleek, modern 7-story medical building that promised answers.",
      },
      {
        h2: "The Surgeon Who Drove Two Hours for Friendship",
        body: "Waiting for me at the entrance was my friend, Dr. Roger — a highly respected surgeon who, and I must emphasize this, had driven two hours from his post at a hospital in another city just to be at my side. That's not a typo. Two hours. One way. For a health screening. This is the kind of friendship that transcends professional courtesy and lands squarely in the territory of \"I don't deserve this man.\"\n\nDr. Roger introduced me to the facility manager, and we headed upstairs. Registration took moments: passport scanned, a custom checklist handed to me like a menu at a fine-dining restaurant. This is a critical advantage for medical tourists — I could choose exactly what I wanted based on my history and the things I'd neglected for a decade. No rigid packages, just \"What do you need, Mr. Dimitropoulos?\" I needed everything.\n\nThe facility itself was spotless and efficient, but I'll be honest: the staff didn't speak English. And that's where the magic of our network comes in. Dr. Roger was my translator, my advocate, and my calming presence. While the phlebotomist prepared her vials, he casually narrated what was happening. For any foreigner nervous about a language barrier, imagine having a trusted bilingual surgeon at your elbow, guiding you through every station. That's the service we provide — and it turned what could have been a clinical anxiety spiral into a strangely pleasant morning stroll through my own biology.",
      },
      {
        h2: "A Parade of Probes and Vials",
        body: "First, the blood draw. Four, maybe five vials. I stopped counting when I realized I hadn't eaten and my veins were probably staging a protest. The technician was swift and silent. Dr. Roger nodded reassuringly. Next, blood pressure, height, weight. (The weight will remain my secret. Hainan's tropical humidity accounts for at least five extra kilos; I'm certain of it.)\n\nThe ECG followed — shirt off, electrodes on, my heart tracing its rhythmic confession on a screen. No drama. The ultrasound was next, and it felt like a guided tour of my own submarine. The technician glided a wand over my neck, mapping my carotid artery, then moved down to my liver, abdomen, kidneys, prostate, and bladder. I watched the grey blobs morph on the monitor and nodded with feigned recognition, as if I could tell a kidney from a cosmic nebula.\n\nThen came the urine test. Ah, the urine test. A small cup, two test tubes, and the command to catch midstream. Picture me, sleep-deprived and uncaffeinated, trying to aim, capture, and then decant the golden essence from a cup into two tiny test tubes without spilling. It was a dexterity challenge no video game could match. I left that bathroom feeling a strange mix of pride and profound humility.",
      },
      {
        h2: "Congee, Chats, and the Heavy Artillery",
        body: "With the samples safely deposited, I was handed a voucher for the in-house cafeteria — a humble Chinese breakfast spread. Dr. Roger and I shared congee and steamed buns, talking not about test results but about life, family, and the peculiar joys of Hainan's tropical pace. He had to head off soon to spend time with his daughter and mother-in-law, but before that, he'd see me through the main event.\n\nA quick stop at the Ear, Nose, and Throat department (no golf balls this time, just a friendly scope and a light), then we descended to the ground floor for the heavy artillery: MRI and CT.\n\nThe cranial MRI was first. I lay on the sliding bed, headphones on, and was fed into a tunnel of industrial techno beats for eight to ten minutes. Slightly claustrophobic? Yes. But I closed my eyes, breathed, and mentally drafted this very article. Within minutes, I was out and ushered directly across the hall to the CT room. No waiting. The technician explained the breathing sequence — hold, exhale, hold — while the machine scanned my lungs. It was over so fast I barely had time to ponder my own existence.",
      },
      {
        h2: "The Giant Coffee at the End of the Tunnel",
        body: "When the last scan was complete, Dr. Roger and I walked out together. He smiled, the calm confidence of a man who knew I'd just done something important. He reminded me that the full results — the bloodwork, urine, MRI, CT — will arrive as a comprehensive PDF. He'll receive them first, translate the medical jargon into plain English for me, and we'll go through every finding, one by one. That's not just service; that's a safety net made of friendship and expertise. He then headed off to enjoy the rest of his day with his daughter and mother-in-law, having given me his entire morning after a two-hour pre-dawn drive. Remarkable.\n\nI, on the other hand, had a more immediate mission. Across the road stood a state-of-the-art modern shopping centre, all glass and curated cool. I wandered in, still buzzing with the caffeine deficit, and found a tiny hole-in-the-wall coffee shop — the kind of cute, independent nook you'd miss if you weren't looking. The barista smiled. I pointed at the menu. She pulled out the largest cup I have ever seen in my life. We're talking a vessel so enormous it could double as a table vase. I looked at it, looked at her, and said, \"That'll be the one for me.\"\n\nMoments later, I was walking out into the Hainan heat, clutching a colossal iced coffee that was half refreshment, half achievement trophy. I sipped it while messaging friends and family, a giddy, sleep-deprived prophet who had just seen the inside of his own skull and lived to caffeinate. Now, I'm heading home to wait for the results. Stay tuned.",
      },
      {
        h2: "Why This Matters (Again)",
        body: "This is the Hainan medical tourism reality. Not a sterile, stressful maze of foreign bureaucracy, but a streamlined journey through a 7-story private facility where your tests are curated, your waits are almost non-existent, and your personal translator — a trusted surgeon who's driven hours just to help — stands beside you the entire time. Yes, the front-line staff may not speak English, but with our network of dedicated bilingual professionals, you'll never feel lost. Dr. Roger will receive my digital report, translate and explain it, and I won't have to guess what a single medical term means.\n\nI spent a decade avoiding a full check-up because I thought it would be too difficult, too alien, too exhausting. It was none of those things. It was a morning, a few vials, a congee break, two scans, and the biggest iced coffee of my life. If I can do it on two and a half hours of sleep and a tank full of anxiety, so can you. Come to Hainan. We'll find you the coffee cup of your dreams when you're done.",
      },
    ],
  },
];

export const journalSlugs = journal.map((p) => p.slug);
